{% set name = "aim" %}
{% set version = "3.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 05a388019b9c59979a329f060a81a4feef0d3a2ed50c7be954583549dde14a7e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - aim=aim.cli.cli:cli_entry_point

requirements:
  host:
    - pip
    - python
    - pysqlite3 ==0.4.6
    - protobuf >=3.11.0
    - anytree >=2.8.0
    - pyrser >=0.2.0
    - psutil >=5.6.7
    - cython >=0.20.0
  run:
    - aimrecords ==0.0.7
    - alembic ==1.6.0
    - anytree >=2.8.0
    - click >=6.7
    - docker-py >=4.1.0
    - flask ==1.1.2
    - flask-cors ==3.0.10
    - flask-migrate
    - flask-restful ==0.3.8
    - flask-script ==2.0.6
    - flask-sqlalchemy ==2.5.1
    - gitpython >=3.0.4
    - gunicorn ==20.1.0  # [not win]
    - protobuf >=3.11.0
    - psutil >=5.6.7
    - py3nvml >=0.2.5
    - pyrser >=0.2.0
    - pysqlite3 ==0.4.6
    - python
    - pytz ==2020.1
    - requests >=2.0.0
    - sqlalchemy ==1.4.13
    - tensorboard ==2.3.0

test:
  imports:
    - aim
    - aim.artifacts
#  commands:
#    - pip check
#    - aim --help
#  requires:
#    - pip

about:
  home: https://github.com/aimhubio/aim
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A super-easy way to record, search and compare 1000s of ML training runs
  dev_url: https://github.com/aimhubio/aim

extra:
  recipe-maintainers:
    - psortos
    - bubblyorca
    - mxr-conda
