{% set name = "aim" %}
{% set version = "4.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aim-{{ version }}.tar.gz
  sha256: 47f7ebc97abcd76b4f447e83b16ba899618efbf31bb4b473137c0ee13ed764d3

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  # NOTE(hadim): windows is not available because of aimrocks missing there
  skip: true  # [win]
  entry_points:
    - aim=aim.cli.cli:cli_entry_point
    - aim-watcher=aim.cli.watcher_cli:cli_entry_point

requirements:
  build:
    - python                                    # [build_platform != target_platform]
    - cross-python_{{ target_platform }}        # [build_platform != target_platform]
    - cython ==3.0.*                            # [build_platform != target_platform]
    - aimrocks ==0.4.0                          # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - make  # [unix]
  host:
    - python
    - pip
    - cython ==3.0.*
    - aimrocks ==0.4.0
  run:
    - importlib-metadata
    - khash ==0.5.0a5
    - segment-analytics-python
    - tabulate
    - watchdog
    - python
    - aim-ui ==4.0.3
    - aimrecords ==0.0.7
    - aimrocks ==0.5.1
    - cachetools >=4.0.0
    - click >=7.0
    - cryptography >=3.0
    - filelock <4,>=3.3.0
    - numpy <2,>=1.12.0
    - psutil >=5.6.7
    - restrictedpython >=5.1
    - tqdm >=4.20.0
    - aiofiles >=0.5.0
    - alembic <2,>=1.5.0
    - fastapi <1,>=0.69.0
    - jinja2 <4,>=2.10.0
    - pytz >=2019.1
    - sqlalchemy >=1.4.1
    - uvicorn <1,>=0.12.0
    - pillow >=8.0.0
    - packaging >=15.0
    - python-dateutil
    - requests
    - websockets
    - boto3

test:
  imports:
    - aim
  commands:
    - pip check
    - aim --help
    - aim-watcher --help
  requires:
    - pip

about:
  home: https://github.com/aimhubio/aim
  license: Apache-2.0
  license_file: LICENSE
  summary: A super-easy way to record, search and compare 1000s of ML training runs
  dev_url: https://github.com/aimhubio/aim

extra:
  recipe-maintainers:
    - gorarakelyan
    - psortos
    - mxr-conda
    - synapticarbors
