{% set name = "aim" %}
{% set version = "3.15.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aim-{{ version }}.tar.gz
  sha256: 933fc88eb661e090799226e1e21b35e0583a17dcf5fd4610c3f57bcb7fcb0d8d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - cython >3
    - aimrocks ==0.2.1
    - protobuf >=3.11.0
  run:
    - python >=3.7
    - aim-ui =={{ version }}
    - aimrecords ==0.0.7
    - aimrocks ==0.2.1
    - cachetools >=4.0.0
    - click >=7.0
    - cryptography >=3.0
    - filelock >=3.3.0
    - numpy >=1.12.0
    - protobuf >=3.11.0
    - psutil >=5.6.7
    - py3nvml >=0.2.5
    - RestrictedPython >=5.1
    - tqdm >=4.20.0
    - aiofiles >=0.5.0
    - alembic >=1.4.0
    - fastapi <0.68.0,>=0.65.0  # see https://github.com/aimhubio/aim/issues/2367
    - jinja2 >=2.10.0
    - pytz >=2019.1
    - SQLAlchemy >=1.4.1
    - uvicorn >=0.12.0
    - Pillow >=8.0.0
    - protobuf <4.0.0,>=3.9.2  # see https://github.com/aimhubio/aim/issues/2455
    - packaging >=15.0
    - python-dateutil
    - requests

test:
  imports:
    - aim
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aimhubio/aim
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A super-easy way to record, search and compare 1000s of ML training runs
  dev_url: https://github.com/aimhubio/aim

extra:
  recipe-maintainers:
    - gorarakelyan
    - psortos
    - mxr-conda
    - hadim
