schema_version: 1

context:
  name: aim
  version: 3.29.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/aim-${{ version }}.tar.gz
  sha256: 30fb70f983844eebd270049206c839e6dc09ce9de500048dc97a7a8b22ed83fb

build:
  # NOTE(hadim): windows is not available because of aimrocks missing there
  number: 0
  skip:
    - win
    - py < 310
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - aim=aim.cli.cli:cli_entry_point
      - aim-watcher=aim.cli.watcher_cli:cli_entry_point

requirements:
  build:
    - if: build_platform != target_platform
      then: python
    - if: build_platform != target_platform
      then: cross-python_${{ target_platform }}
    - if: build_platform != target_platform or build_platform != target_platform
      then: cython ==3.0
    - if: build_platform != target_platform or build_platform != target_platform
      then: aimrocks ==0.5
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - if: unix
      then: make
  host:
    - python
    - pip
    - setuptools
    - cython ==3.0
    - aimrocks ==0.5
  run:
    - python
    - aim-ui => 3.27, <4.0
    - aimrecords ==0.0.7
    - aimrocks ==0.5.2
    - cachetools >=4.0.0
    - click >=7.0
    - cryptography >=3.0
    - filelock <4,>=3.3.0
    - numpy <3,>=1.12.0
    - psutil >=5.6.7
    - restrictedpython >=5.1
    - tqdm >=4.20.0
    - aiofiles >=0.5.0
    - alembic <2,>=1.5.0
    - fastapi <1,>=0.69.0
    - jinja2 <4,>=2.10.0
    - pytz >=2019.1
    - sqlalchemy >=1.4.1
    - uvicorn <1,>=0.12.0
    - pillow >=8.0.0
    - packaging >=15.0
    - python-dateutil
    - requests
    - websockets
    - boto3

tests:
  - python:
      imports:
        - aim
  - requirements:
      run:
        - pip
    script:
      - pip check
      - aim --help
      - aim-watcher --help

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: A super-easy way to record, search and compare 1000s of ML training runs
  homepage: https://github.com/aimhubio/aim
  repository: https://github.com/aimhubio/aim

extra:
  recipe-maintainers:
    - gorarakelyan
    - psortos
    - mxr-conda
    - synapticarbors
    - maresb

