conda_build_tool: rattler-build
conda_forge_output_validation: true
build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
  osx_arm64: osx_64
github:
  branch_name: main
  tooling_branch_name: main
test: native_and_emulated
bot:
  automerge: false
  inspection: update-grayskull
